---
name: docker

on:
  push:
    paths-ignore:
      - "**.md**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
